# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read VCF compressed with gzip/bgzip
#'
#' This function reads a compressed gzip/bgzip files and returns 
#' a genotype matrix of size [# variants] x [# samples].
#' 
#' @param filename A file name of a compressed VCF file ending with .gz or .bgz
#' @return A integer genotype matrix of a size [# variants] x [# samples]. 
#'         Only GT field will be recognized. The row names will be variant IDs, 
#'         in the format of [CHROM]:[POS]:[REF]:[ALT], and the column names 
#'         will be the sample IDs
#' @examples
#' fpath = system.file("extdata",
#'   "1000G_exome_chr20_example_softFiltered.calls.vcf.gz",
#'   package="tinyVcfReader")
#' mat = readVcf(fpath)
#' dim(mat)
#' @export
readVcf <- function(filename) {
    .Call('_tinyVcfReader_readVcf', PACKAGE = 'tinyVcfReader', filename)
}

